/*
* SIMATIC IT Unified Architecture for Process Industries V1.1.
* Copyright (C) Siemens AG 2017. All Rights Reserved.
*/


(function () {
    'use strict';

    angular
        .module('Siemens.SimaticIT.UAPI.PICore')
        .directive('sitPiMtuCreate', mtuCreateDirective);

    function mtuCreateDirective() {
        return {
            templateUrl: 'Siemens.SimaticIT.UAPI.PICore/widgets/mtuCreate/mtu-create.html',
            controller: mtuCreateController,
            restrict: 'E',
            controllerAs: 'vm',
            scope: {},
            bindToController: {
                onRegisterCreateApi: '&'
            }
        };
    }

    mtuCreateController.$inject = [
        '$scope',
        'common.base',
        'common.services.logger.service',
        'Siemens.SimaticIT.UAPI.PICore.service',
        'common.widgets.messageOverlay.service',
        '$translate',
        'Siemens.SimaticIT.UAPI.PICore.extensionService',
        'Siemens.SimaticIT.UAPI.PICore.commonService'
    ];
    function mtuCreateController(
        $scope,
        common,
        loggerService,
        dataService,
        messageOverlay,
        $translate,
        extService,
        commonService) {
        var vm = this;
        var logger;
        var toBeDestroyed = [];
        vm.customData = {};
        vm.extPropertiesObject = null;
        init();
        vm.notCanceled = true;
        vm.isCancelBtnVisible = true;
        var extCmdToCall;
        vm.translatedNId = $translate.instant('picore.headers.propertyGrids.nId');
        vm.translatedName = $translate.instant('picore.headers.propertyGrids.name');
        vm.translatedDescription = $translate.instant('picore.headers.propertyGrids.description');
        vm.translatedTemplate = $translate.instant('picore.headers.propertyGrids.template');
        vm.translatedMaterial = $translate.instant('picore.headers.propertyGrids.materialNId');
        vm.translatedQuantity = $translate.instant('picore.headers.propertyGrids.quantity');
        vm.translatedUoM = $translate.instant('picore.headers.propertyGrids.uoM');
        vm.translatedSave = $translate.instant('picore.buttonsAndTooltips.save');
        vm.translatedCancel = $translate.instant('picore.buttonsAndTooltips.cancel');
        vm.translatedAutogeneratedId = $translate.instant('picore.headers.propertyGrids.autogeneratedId');
        vm.translatedAutogeneratedName = $translate.instant('picore.headers.propertyGrids.autogeneratedName');
        vm.translatedDefaultTemplate = $translate.instant('picore.headers.propertyGrids.useDefaultTemplate');
        vm.translatedMaterialRevision = $translate.instant('picore.headers.propertyGrids.materialRev');
        vm.translatedMaterialLot = $translate.instant('picore.headers.propertyGrids.materialLotNId');
        vm.translatedPlaces = $translate.instant('picore.headers.propertyGrids.places');
        var validExtInputs;
        var validInputs;
        function init() {
            logger = loggerService.getModuleLogger('mtuCreate directive...');
            vm.removeOverlay = removeOverlay;
            vm.displayOverlay = displayOverlay;
            vm.isComponentTitleVisible = true;
            vm.mtuData = {};
            vm.isEdit = false;
            vm.ngReadonly = false;
            vm.notCanceled = true;
            vm.mtuTplData = [];
            vm.materialsData = {};
            vm.materialsAndRevisionData = [];
            vm.materialRevisions = {};
            vm.uomData = [];
            vm.lotData = [];
            vm.places = [{ nid: 'Equipment', id: 'Equipment' }, { nid: 'Location', id: 'Location' }];
            vm.noMTUPatternNId = false;
            vm.noMTUPatternName = true;
            vm.UoM = {};
            vm.save = save;
            vm.cancel = cancel;
            vm.mtuId = '';
            vm.reset = reset;
            vm.currentData = {
                MaterialRevision: '',
                disabledID: false,
                disabledName: false,
                disabledTemplate: false,
                AutogeneratedId: [{ checked: false }],
                AutogeneratedName: [{ checked: false }],
                DefaultTemplate: [{ checked: false }]
            };
            vm.disableID = disableID;
            vm.disableName = disableName;
            vm.disableTemplate = disableTemplate;
            vm.noDefaultTemplate = false;
            vm.setRevisions = setRevisions;
            vm.setTemplate = setTemplate;
            vm.lotChange = lotChange;
            vm.uoMChange = uoMChange;
            vm.setRevision = setRevision;
            vm.revDisabled = false;
            vm.lotDisabled = true;
            vm.NameEqNId = false;
            vm.mtuPropertyExtData = [];
            vm.api = {
                editMtu: editMtu,
                setExtendedProperties: setExtendedProperties,
                showTitle: showTitle,
                showCancelButton: showCancelButton
            };
            vm.title = $translate.instant('picore.titles.createMTUTitle');

            vm.onRegisterCreateApi({ api: vm.api });

            dataService.getMtuTemplates('$select=NId,Name,IsDefault')
                .then(onGetMTUTemplatesSuccess, function (reason) {
                    logger.logErr('Error Material tracking unit templates', reason);
                });
            dataService.getMaterials('$select=NId,Name,Revision,UoMNId,IsCurrent&$orderby=NId%20asc')
                .then(onGetMaterialSuccess, function (reason) {
                    logger.logErr('Error getting materials', reason);
                });
            dataService.getMTUNumberingPattern('$select=NId,NumberingPatternParts')
                .then(onGetMTUNumberingSuccess, function (reason) {
                    logger.logErr('Error getting numbering pattern', reason);
                });
            dataService.getUoMs('$select=NId,Id,Name')
                .then(onGetUoMSuccess, function (reason) {
                    logger.logErr('Error getting unit of measures', reason);
                });
            registerEvents();
            setData();
        }

        function setExtendedProperties(extendedEntityNames, extendedFacetNames, extPropertiesObject, saveCmdExt, mtuData) {
            vm.extPropertiesObject = extPropertiesObject;
            vm.mtuPropertyExtData = commonService.applyPropertyGridColumnsConfiguration(extPropertiesObject, true);
            extCmdToCall = saveCmdExt;
            if (extPropertiesObject) {
                commonService.applyValuesToConfiguredSitPropertyGridFields(vm.mtuPropertyExtData, mtuData);
            }
        }

        function showTitle(isVisible) {
            vm.isComponentTitleVisible = isVisible;
        }

        function showCancelButton(isVisible) {
            vm.isCancelBtnVisible = isVisible;
        }

        function editMtu(mtuId) {
            vm.title = '';

            if (mtuId) {
                dataService.getById(mtuId).then(onGetMtuByIdSuccess, function (reason) { logger.logErr('Error getting MTU details', reason); });
                vm.currentData.disabledID = true;
                vm.noMTUPatternNId = true;
                vm.isEdit = true;
            }
        }

        function reset() {
            $scope.$broadcast('xor-Reset');
            vm.currentData = {
                disabledID: false,
                disabledName: false,
                disabledTemplate: false,
                AutogeneratedId: [{ checked: false }],
                AutogeneratedName: [{ checked: false }],
                DefaultTemplate: [{ checked: false }]
            };

            setData();
        }

        function customReset() {
            $scope.$broadcast('xor-Reset');
            for (var i = 0; i < vm.mtuPropertyExtData.length; i++) {
                var propertyName = vm.mtuPropertyExtData[i].id;
                for (var j = 0; j < vm.extPropertiesObject.length; j++) {
                    if (vm.extPropertiesObject[i].PropertyName === propertyName) {
                        propertyName = vm.extPropertiesObject[i].Id;
                        break;
                    }
                }
                if (vm.mtuPropertyExtData[i].widget !== 'sit-checkbox') {
                    vm.customData[propertyName] = '';
                    vm.mtuPropertyExtData[i].value = '';
                } else {
                    vm.customData[propertyName] = [{ checked: false }];
                    vm.mtuPropertyExtData[i].value = [{ checked: false }];
                }
            }
        }

        function disableID() {
            vm.currentData.disabledID = !vm.currentData.disabledID;
        }

        function disableName() {
            vm.currentData.disabledName = !vm.currentData.disabledName;
        }

        function disableTemplate() {
            vm.currentData.disabledTemplate = !vm.currentData.disabledTemplate;
        }

        function registerEvents() {
            toBeDestroyed[toBeDestroyed.length] = $scope.$on('sit-property-grid.validity-changed', onPropertyGridValidityChange);
            $scope.$on('$destroy', deregisterEvents);
        }

        function deregisterEvents() {
            for (var i = 0; i < toBeDestroyed.length; i++) {
                toBeDestroyed[i] = null;
            }
        }

        function onPropertyGridValidityChange(event, params) {
            if (params.id === 'mtuPropertyExt') {
                validExtInputs = params.validity;
            }
            if (params.id === 'mtuProperty') {
                validInputs = params.validity;
            }
            vm.validInputs = validExtInputs && validInputs;
        }

        function save() {
            if (vm.currentData.disabledID && !vm.noMTUPatternNId) {
                vm.currentData.NId = '\u0091NId';
            }

            if (vm.currentData.disabledName && (!vm.noMTUPatternNIame)) {
                vm.currentData.Name = '\u0091Name';
            }
            gatherAndManageExtendedCurrentData();
            if (!vm.isEdit) {
                if ((vm.currentData.MaterialNId !== undefined && (vm.currentData.MaterialRevision !== undefined || vm.currentData.MaterialRevision !== ''))
                    || (vm.currentData.MaterialNId === undefined && (vm.currentData.MaterialRevision === undefined || vm.currentData.MaterialRevision === '')
                    && vm.currentData.Quantity === undefined && vm.currentData.QuantityUoMNId === undefined)) {
                    if (extCmdToCall === '' || extCmdToCall === null || extCmdToCall === undefined) {
                        dataService.createMtu(vm.currentData).then(onCreationSuccess, function (reason) {
                            logger.logErr('Error creating material tracking unit', reason);
                            vm.validInputs = false;
                        });
                    } else {
                        extService.createMtuExt(extCmdToCall, vm.currentData, vm.customData).then(onExtendedCreationSuccess, function (reason) {
                            logger.logErr('Error creating material Ext tracking unit', reason);
                            vm.validInputs = false;
                        });
                    }

                } else {
                    dataService.createMtuNoQty(vm.currentData).then(onCreationNoMatButQtySuccess, function (reason) {
                        logger.logErr('Error creating material tracking unit', reason);
                        vm.validInputs = false;
                    });
                }
            } else {
                vm.input = vm.currentData;
                if (vm.currentData.MaterialRevision === null) {
                    vm.input.MaterialRevision = { revision: '' };
                }
                if (extCmdToCall === '' || extCmdToCall === null || extCmdToCall === undefined) {
                    dataService.updateMtu(vm.input).then(onUpdateMtuSuccess, onEditMtuError);
                } else {
                    extService.updateMtuExt(extCmdToCall, vm.currentData, vm.customData).then(onExtendedUpdateSuccess, function (reason) {
                        logger.logErr('Error updating Extended material tracking unit', reason);
                        vm.validInputs = false;
                    });
                }
            }
        }

        function onExtendedUpdateSuccess(result) {
            vm.mtuId = result.data.MaterialTrackingUnitId;
            $scope.$emit('MTUCreated', vm.mtuId);
            vm.validInputs = false;
            setData();
            reset();
            customReset();
        }

        function gatherAndManageExtendedCurrentData() {
            for (var i = 0; i < vm.mtuPropertyExtData.length; i++) {
                var propertyName = vm.mtuPropertyExtData[i].id;
                for (var j = 0; j < vm.extPropertiesObject.length; j++) {
                    if (vm.extPropertiesObject[i].PropertyName === propertyName) {
                        propertyName = vm.extPropertiesObject[i].Id;
                        break;
                    }
                }
                switch (vm.mtuPropertyExtData[i].widget) {
                    case 'sit-checkbox':
                        vm.customData[propertyName] = vm.mtuPropertyExtData[i].value[0].checked;
                        break;
                    case 'sit-date-time-picker':
                        if (vm.mtuPropertyExtData[i].value !== '') {
                            vm.customData[propertyName] = vm.mtuPropertyExtData[i].value;
                        } else {
                            vm.customData[propertyName] = [];
                        }
                        break;
                    default:
                        vm.customData[propertyName] = vm.mtuPropertyExtData[i].value;

                }

            }
        }

        function onUpdateMtuSuccess() {
            $scope.$emit('MTUUpdated', vm.mtuId);
        }

        function onEditMtuError(reason) {
            var code = reason.data.error.errorCode;
            if (code === -20) {

                logger.logErr('Error updating material tracking unit', reason);
                vm.validInputs = false;
                vm.overlay = {
                    text: $translate.instant('picore.notifications.errors.missingMaterial'),
                    title: $translate.instant('picore.titles.error.Title'),
                    buttons: [{
                        id: 'okButton',
                        displayName: $translate.instant('picore.buttonsAndTooltips.ok'),
                        onClickCallback: function () {
                            removeOverlay();
                        }
                    }]
                };

                messageOverlay.set(vm.overlay);
                displayOverlay();
            }
        }

        function cancel() {
            reset();
            $scope.$emit('MTUCreationCancel', vm.mtuId);
        }

        function onGetMtuByIdSuccess(data) {

            if (data.value.length > 0) {
                angular.forEach(data.value[0], function (value, key) {
                    if (key === 'Quantity') {
                        if (value.QuantityValue !== null) {
                            vm.currentData.Quantity = parseFloat(value.QuantityValue);
                        }
                        if (value.UoMNId !== null) {
                            vm.uomData = [];
                            vm.currentData.QuantityUoMNId = { nid: value.UoMNId };
                        }
                        dataService.getUoMByNId(value.UoMNId, '$select=Id,NId,Name,UoMBase_Id')
                            .then(onGetUoMSuccessGetRelated, function (reason) {
                                logger.logErr('Error getting unit of measures', reason);
                            });
                    } else if (key === 'MaterialNId') {
                        vm.currentData.MaterialNId = { id: value };
                    } else if (key === 'MaterialRevision') {
                        vm.currentData.MaterialRevision = { revision: value };
                    } else if (key === 'TemplateNId') {
                        vm.currentData.TemplateNId = { id: value };
                    } else if (key === 'MaterialLot_Id') {
                        vm.currentData.MaterialLot = { id: value };
                    } else {
                        vm.currentData[key] = value;
                    }
                });
                logger.logInfo('currentData', vm.currentData);
            }
            setData();
        }

        function onCreationSuccess(result) {
            vm.mtuId = result.data.MaterialTrackingUnitId;
            $scope.$emit('MTUCreated', vm.mtuId);
            vm.validInputs = false;
            setData();
            reset();
        }

        function onExtendedCreationSuccess(result) {
            vm.mtuId = result.data.MaterialTrackingUnitId;
            $scope.$emit('MTUCreated', vm.mtuId);
            vm.validInputs = false;
            setData();
            reset();
            customReset();
        }

        function removeOverlay() {
            messageOverlay.hide();
        }

        function displayOverlay() {
            messageOverlay.show();
        }

        function onCreationNoMatButQtySuccess(result) {
            vm.mtuId = result.data.MaterialTrackingUnitId;
            var params = {
                'Id': vm.mtuId,
                'Quantity': {
                    QuantityValue: vm.currentData.Quantity,
                    UoMNId: vm.currentData.QuantityUoMNId === undefined ? vm.currentData.QuantityUoMNId : vm.currentData.QuantityUoMNId.nid
                }
            };
            dataService.setMaterialTrackingUnitQuantity(params).then(onSetMaterialTrackingUnitQuantitySuccess, function (reason) {
                logger.logErr('Error updating material tracking unit quantity', reason);
                vm.overlay = {
                    text: $translate.instant('picore.notifications.warnings.warningMtuCreatedButNoQuantitySet'),
                    title: $translate.instant('picore.titles.warningTitle'),
                    buttons: [{
                        id: 'okButton',
                        displayName: $translate.instant('picore.buttonsAndTooltips.ok'),
                        onClickCallback: function () {
                            removeOverlay();
                        }
                    }]
                };

                messageOverlay.set(vm.overlay);
                displayOverlay();
            });
            vm.validInputs = false;
            setData();

            reset();
        }

        function onSetMaterialTrackingUnitQuantitySuccess() {
            $scope.$emit('MTUCreated', vm.mtuId);
        }

        function onGetMaterialSuccess(data) {
            vm.tempCurrentData = {};
            vm.materialsAndRevisionData = [];
            vm.materialsData = [];
            var setMaterialNId = false;
            for (var i = 0; i < data.value.length; i++) {
                var found = false;
                for (var j = 0; j < vm.materialsData.length; j++) {
                    if (data.value[i].NId === vm.materialsData[j].id) {
                        found = true;
                        vm.materialsData[j] = { id: data.value[i].NId, name: data.value[i].Name, uomNid: data.value[i].UoMNId };
                    }
                }
                if (found === false) {
                    vm.materialsData.push({ id: data.value[i].NId, name: data.value[i].Name, uomNid: data.value[i].UoMNId });
                }
                vm.materialsAndRevisionData.push({
                    id: data.value[i].NId,
                    name: data.value[i].Name,
                    revision: data.value[i].Revision,
                    uomNid: data.value[i].UoMNId,
                    IsCurrent: data.value[i].IsCurrent
                });
                if (vm.tempCurrentData.MaterialNId !== undefined && vm.tempCurrentData.MaterialNId.id === data.value[i].NId) {
                    setMaterialNId = true;
                    vm.tempCurrentData.MaterialNId = { id: data.value[i].NId, name: data.value[i].Name, uomNid: data.value[i].UoMNId };
                }
            }
            vm.widgetAttributesMaterial = {
                'sit-options': vm.materialsData,
                'sit-to-display': 'id',
                'sit-to-keep': 'id'
            };
            if (setMaterialNId === true) {
                vm.currentData.MaterialNId = vm.tempCurrentData.MaterialNId;
            }

        }

        function setRevisions(oldVal, newVal) {
            if (newVal !== undefined && newVal.nid !== null) {
                if (vm.materialsData[0].id !== '') {
                    vm.materialsData.unshift({ id: '', name: '', uomNid: '' });
                } else {
                    if (vm.uomData.length > 0 && vm.uomData[0].nid === '') {
                        vm.uomData.shift();
                    }
                }
            }
            if (newVal) {
                vm.currentData.MaterialLot = {};
                vm.materialRevisions = [];
                if (newVal.id === '' || newVal.id === null) {
                    if (vm.currentData.QuantityUoMNId !== null) {
                        vm.currentData.QuantityUoMNId = { nid: null };
                        vm.currentData.MaterialNId = { nid: null };
                        vm.uomData = [];
                    }
                    if (vm.materialsData[0].id === '') {
                        vm.materialsData.shift();
                    }
                    dataService.getUoMs('$select=NId,Id,Name').then(onGetUoMSuccess, function (reason) { logger.logErr('Error getting unit of measures', reason); });
                }
                var ind = 0;
                var indCurrent = -1;
                var setMaterialRevision = false;
                for (var i = 0; i < vm.materialsAndRevisionData.length; i++) {
                    if (newVal.id !== undefined && newVal.id === vm.materialsAndRevisionData[i].id) {
                        vm.materialRevisions.push({
                            id: vm.materialsAndRevisionData[i].id,
                            name: vm.materialsAndRevisionData[i].name,
                            revision: vm.materialsAndRevisionData[i].revision,
                            uomNid: vm.materialsAndRevisionData[i].uomNid,
                            IsCurrent: vm.materialsAndRevisionData[i].IsCurrent
                        });
                        ind++;
                        if (vm.materialsAndRevisionData[i].IsCurrent === true) {
                            indCurrent = ind;
                        }
                        if (vm.tempCurrentData.MaterialNId !== undefined && vm.tempCurrentData.MaterialRevision !== undefined) {
                            if (vm.tempCurrentData.MaterialNId.id === vm.materialsAndRevisionData[i].id
                                && vm.tempCurrentData.MaterialRevision.revision === vm.materialsAndRevisionData[i].revision) {
                                setMaterialRevision = true;
                                vm.tempCurrentData.MaterialRevision = {
                                    id: vm.materialsAndRevisionData[i].id,
                                    name: vm.materialsAndRevisionData[i].name,
                                    revision: vm.materialsAndRevisionData[i].revision,
                                    uomNid: vm.materialsAndRevisionData[i].uomNid
                                };
                            }
                        }
                    }
                }
                if (ind === 0) {
                    vm.currentData.MaterialRevision = {};
                } else if (ind === 1) {
                    vm.currentData.MaterialRevision = vm.materialRevisions[0];
                } else if (ind !== 1 && indCurrent !== -1) {
                    vm.currentData.MaterialRevision = vm.materialRevisions[indCurrent - 1];
                } else {
                    vm.currentData.MaterialRevision = '';
                }

                vm.widgetAttributesMaterialRevision = {
                    'sit-options': vm.materialRevisions,
                    'sit-to-display': 'revision',
                    'sit-to-keep': 'revision'
                };
                if (newVal.uomNid) {
                    vm.uomData = [];
                    dataService.getUoMByNId(newVal.uomNid, '$select=Id,NId,Name,UoMBase_Id')
                        .then(onGetUoMSuccessGetRelated, function (reason) {
                            logger.logErr('Error getting unit of measures', reason);
                        });
                } else if (newVal.uomNid === '') {
                    vm.currentData.QuantityUoMNId = { id: '', nid: '' };
                }
                if (setMaterialRevision === true) {
                    vm.currentData.MaterialRevision = vm.tempCurrentData.MaterialRevision;
                }
            }
        }

        function setRevision(oldVal, newVal) {
            if (newVal) {
                vm.currentData.MaterialLot = {};
                vm.lotData = [];
                if (vm.materialRevisions.length > 0 && vm.materialRevisions[0].revision !== '') {
                    vm.materialRevisions.unshift({ revision: '' });
                }
                dataService.getLotsByMaterial(newVal, '$select=NId,Name,MaterialRevision')
                    .then(onGetLotSuccess, function (reason) {
                        logger.logErr('Error getting lots', reason);
                    });
            }
        }

        function lotChange(oldVal) {
            if (vm.lotData && vm.lotData.length > 0 && vm.lotData[0].id !== '') {
                vm.lotData.unshift({ id: '' });
            }
        }

        function setTemplate() {
            if (vm.mtuTplData && vm.mtuTplData.length > 0 && vm.mtuTplData[0].id !== '') {
                vm.mtuTplData.unshift({ id: '' });
            }
        }

        function uoMChange(oldVal, newVal) {
            if (newVal === null || newVal === undefined || (newVal.nid === '' || newVal.nid === null)) {
                if (vm.uomData.length > 0 && vm.uomData[0].nid === '') {
                    vm.uomData.shift();
                }
                vm.currentData.QuantityUoMNId = null;
            } else {
                if (vm.uomData.length > 0 && vm.uomData[0].nid !== '') {
                    vm.uomData.unshift({ nid: '' });
                }
            }
        }

        function onGetMTUNumberingSuccess(data) {
            if (data.value.length === 0) {
                vm.noMTUPatternNId = true;
                vm.noMTUPatternName = true;
            } else if (data.value.length === 1) {
                if (data.value[0].NId.toLowerCase() === 'nid' && data.value[0].NumberingPatternParts.length > 0) {
                    vm.noMTUPatternNId = false;
                    vm.noMTUPatternName = true;
                } else if (data.value[0].NId.toLowerCase() === 'name' && data.value[0].NumberingPatternParts.length > 0) {
                    vm.noMTUPatternNId = true;
                    vm.noMTUPatternName = false;
                }
            } else if (data.value.length === 2) {
                if ((data.value[0].NId.toLowerCase() === 'nid' && data.value[0].NumberingPatternParts.length > 0)
                    || (data.value[1].NId.toLowerCase() === 'nid' && data.value[1].NumberingPatternParts.length > 0)) {
                    vm.noMTUPatternNId = false;
                    if ((data.value[0].NId.toLowerCase() === 'name' && data.value[0].NumberingPatternParts.length > 0)
                        || (data.value[1].NId.toLowerCase() === 'name' && data.value[1].NumberingPatternParts.length > 0)) {
                        vm.noMTUPatternName = false;
                    } else {
                        vm.noMTUPatternName = true;
                    }
                } else if ((data.value[0].NId.toLowerCase() === 'name' && data.value[0].NumberingPatternParts.length > 0)
                    || (data.value[1].NId.toLowerCase() === 'name' && data.value[1].NumberingPatternParts.length > 0)) {
                    vm.noMTUPatternName = false;
                    if ((data.value[0].NId.toLowerCase() === 'nid' && data.value[0].NumberingPatternParts.length > 0)
                        || (data.value[1].NId.toLowerCase() === 'nid' && data.value[1].NumberingPatternParts.length > 0)) {
                        vm.noMTUPatternNId = false;
                    } else {
                        vm.noMTUPatternName = true;
                    }
                }
            }
        }

        function onGetMTUTemplatesSuccess(data) {
            vm.noDefaultTemplate = true;
            if (data.value.length <= 0) {
                vm.noDefaultTemplate = true;
            }
            for (var i = 0; i < data.value.length; i++) {
                if (data.value[i].IsDefault) {
                    vm.noDefaultTemplate = false;
                }
                vm.mtuTplData[i] = { id: data.value[i].NId, name: data.value[i].Name };
            }
        }

        function onGetUoMSuccess(data) {
            for (var i = 0; i < data.value.length; i++) {
                vm.uomData[i] = { id: data.value[i].Id, nid: data.value[i].NId, name: data.value[i].Name };
            }
            setData();
        }

        function onGetUoMSuccessGetRelated(data) {
            if (data.value.length === 1) {
                vm.UoM = { id: data.value[0].Id, nid: data.value[0].NId, name: data.value[0].Name, uomBaseId: data.value[0].UoMBase_Id };
                dataService.getRelatedUoMs(data.value[0], '$select=NId')
                    .then(onGetRelatedUoMSuccess, function (reason) {
                        logger.logErr('Error getting related unit of measures', reason);
                    });
            }
        }

        function onGetRelatedUoMSuccess(data) {
            var cnt = data.value.length;
            if (data.value.length === 0) {
                vm.baseUoM = vm.UoM;
                vm.uomData[0] = vm.UoM;
            } else if (data.value.length === 1) {
                if (data.value[0].UoMBase_Id === null) {
                    vm.baseUoM = { id: data.value[0].Id, nid: data.value[0].NId, name: data.value[0].Name, uomBaseId: data.value[0].UoMBase_Id };
                    dataService.getRelatedUoMs(data.value[0], '$select=NId')
                        .then(onGetRelatedUoMSuccess, function (reason) {
                            logger.logErr('Error getting related unit of measures', reason);
                        });
                }
            } else {
                if (vm.baseUoM && vm.baseUoM.id !== data.value[0].UoMBase_Id) {
                    vm.baseUoM = null;
                }
                for (var i = 0; i < cnt ; i++) {
                    vm.uomData[i] = { id: data.value[i].Id, nid: data.value[i].NId, name: data.value[i].Name };

                }
                if (vm.baseUoM) {
                    vm.uomData[cnt] = vm.baseUoM;
                }
                if (!vm.baseUoM && vm.UoM) {
                    vm.uomData[cnt] = vm.UoM;
                }
            }
            vm.currentData.QuantityUoMNId = vm.UoM;
            if (vm.uomData.length > 0 && vm.uomData[0].nid !== '') {
                vm.uomData.unshift({ nid: '' });
            }
            setData();
        }

        function onGetLotSuccess(data) {
            if (data.value.length === 0) {
                vm.lotDisabled = true;
            }
            for (var i = 0; i < data.value.length; i++) {
                vm.lotData[i] = { id: data.value[i].NId, name: data.value[i].Name, revision: data.value[i].MaterialRevision };
                vm.lotDisabled = false;
                if (data.value.length === 1) {
                    vm.currentData.MaterialLot = { id: data.value[0].NId, name: data.value[0].Name, revision: data.value[0].MaterialRevision };
                } else {
                    vm.lotDisabled = false;
                }
            }
            setData();
        }

        function setData() {
            vm.widgetAttributesMaterial = {
                'sit-options': vm.materialsData,
                'sit-to-display': 'id',
                'sit-to-keep': 'id'
            };
            vm.widgetAttributesMaterialRevision = {
                'sit-options': vm.materialRevisions,
                'sit-to-display': 'revision',
                'sit-to-keep': 'revision'
            };
            vm.widgetAttributesTemplate = {
                'sit-options': vm.mtuTplData,
                'sit-to-display': 'id',
                'sit-to-keep': 'id'
            };
            vm.widgetAttributesUoM = {
                'sit-options': vm.uomData,
                'sit-to-display': 'nid',
                'sit-to-keep': 'nid'
            };
            vm.widgetAttributesMaterialLot = {
                'sit-options': vm.lotData,
                'sit-to-display': 'id',
                'sit-to-keep': 'id'
            };
            vm.widgetAttributesPlaces = {
                'sit-pi-options': vm.places,
                'sit-pi-to-display': 'nid',
                'sit-pi-to-keep': 'id'
            };
        }
    }
})();
